### ISSUE TITLE
Create a pull request template to standardize pull requests

### ISSUE THREAD

**Issue by SangamSwadiK** [data-umbrella/data-umbrella-website#22]
**Dependencies** :  #21  Needs to be merged before this could be done

@reshamas 
Please let me know if you have some good templates. 
I found couple of them, and looked into some  popular libraries too.

Thanks.

**Comment by reshamas** [comment]
@SangamSwadiK I've no experience with templates for PRs, it's a great idea!
Let's go through this at our next website meeting and set up a template or two.
