### ISSUE TITLE
typo: change global sprint year from 2021 to 2020

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/data-umbrella-website#37]
In this file:
https://github.com/data-umbrella/data-umbrella-website/blob/main/snowlake-v1.2/_data/navigation.yml

change from 2021 to 2020:
current:
line 45
```
      - text: "scikit-learn Global: Jun 2021"
```
to:
```
      - text: "scikit-learn Global: Jun 2020"
```

**Comment by mohameddjebloun** [comment]
Hey this looks quite simple to do I think I can do it

**Comment by reshamas** [comment]
@mohameddjebloun 
It looks like someone already submitted a PR on this.

Next time, you can say you are working on the issue and submit a pull request.
