### ISSUE TITLE
"Sprint Reports" page: add reflections blog

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/data-umbrella-website#64]
Page: 
https://dev.dataumbrella.org/open-source/index-8.html

To do:  
- [x] rename file from "index-8.html" to sprint_reports.html
- [x] add comment at top of "sprint_reports.html" file:  <- template used: index-8.html ->
- [x] update [navigation bar](https://github.com/data-umbrella/data-umbrella-website/blob/main/snowlake-v1.2/_data/navigation.yml)
    - [x] to point to new file name: sprint_reports.html
    - [x] change menu label from "Sprint report" to "Sprint Reports"
- [x] add this report for the PyMC Feb 2022 event to "sprint_reports.html": https://blog.dataumbrella.org/pymc-sprint-summary

**Comment by CoffeeGeek101** [comment]
@reshamas I hope you are having a good day. I would to work on this issue.

**Comment by CoffeeGeek101** [comment]
@SangamSwadiK Okay, I'm on it.

**Comment by CoffeeGeek101** [comment]
@reshamas can you explain the "update nav bar" expected behaviour or changes?

**Comment by reshamas** [comment]
> @reshamas can you explain the "update nav bar" expected behaviour or changes?

Info on nav bar is here:  
https://github.com/data-umbrella/data-umbrella-website/issues/35
