### ISSUE TITLE
website deployment on Netlify

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/data-umbrella-website#8]
deployment:  Netlify
https://www.netlify.com/pricing/
PR previews

dev.xxx.org

**Comment by reshamas** [comment]
@symeneses I deployed the website on Netlify at:
https://dev.dataumbrella.org/

It says "page not found".
https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking

It may be possible that the `index.html` file needs to be at the root level?

cc:  @SangamSwadiK

**Comment by symeneses** [comment]
In Netlify, there is an option to select a path to the code `Base directory`.  Is this set  `snowlake-v1.2`?

**Comment by reshamas** [comment]
I updated the base directory here. Let's see if that works?
https://app.netlify.com/sites/majestic-souffle-d006f2/settings/deploys

<img width="722" alt="Screen Shot 2022-12-08 at 8 44 15 AM" src="https://user-images.githubusercontent.com/2507232/206461694-c92e6067-0fd7-403b-82ec-880d9f08314f.png">

**Comment by reshamas** [comment]
@symeneses This is what it is set to now:
<img width="712" alt="Screen Shot 2022-12-13 at 10 21 59 AM" src="https://user-images.githubusercontent.com/2507232/207373207-1f3d85b1-2133-477e-a956-cfb8dec9d34c.png">

**Comment by reshamas** [comment]
@symeneses
Would it be best to bring all the files under the "snowflake" folder up a level, as we discussed?
Since most Jekyll websites are structured that way.

If the above doesn't work, then we should bring the files up a level, because it seems Netlify (probably event GH pages) is expecting an `index.html` file at the root level. 

cc: @SangamSwadiK

**Comment by symeneses** [comment]
PR to add Gemfile.lock which is needed according to the docs. After this is merged, we can see the configuration in Netlify.

**Comment by reshamas** [comment]
@SangamSwadiK 
Not sure I understand.
Do I update Google Domains to this:  [precious-bubblegum-ae4b85.netlify.app](https://precious-bubblegum-ae4b85.netlify.app/)

**Comment by reshamas** [comment]
@SangamSwadiK 
These are current settings here:  https://app.netlify.com/sites/majestic-souffle-d006f2/settings/deploys

<img width="722" alt="Screen Shot 2022-12-16 at 11 25 13 AM" src="https://user-images.githubusercontent.com/2507232/208143665-f85ab3d7-bc16-4ac8-895a-d70b3ca7384d.png">
